fix nf_elem_fmpz_sub
flintlib/antic pull request #34
Opened 2019-08-23 13:21 UTC by fieker

seems to work better - copied from the si_sub file....

2019-08-23 14:11 UTC, wbhart requested changes

2019-08-23 14:11 UTC, wbhart commented on nf_elem/fmpz_sub.c
> +          for(i = 0; i <= len; i++)
Why is is <= instead of < ? I'm probably just missing something obvious.

2019-08-23 15:25 UTC, fieker commented
On Fri, Aug 23, 2019 at 07:11:39AM -0700, wbhart wrote:
> wbhart requested changes on this pull request.
> 
> 
> 
> >  	  
>  	  nf_elem_set(a, b, nf);
>  	  
>  	  while (len != 0 && fmpz_is_zero(num + len - 1))
>  	     len--;
> -	  
> -      fmpz_submul(num, den, c);
> -	  fmpz_neg(num, num);
> +
> +
> +          fmpz_submul(num, den, c);
> +
> +          for(i = 0; i <= len; i++)
> 
> Why is is <= instead of < ? I'm probably just missing something obvious.
> 
the while loop ends with len being the last non-zero term. Thus it needs
negating.
Other answer: it is copied from the nf_elem_si_sub case
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/wbhart/antic/pull/34#pullrequestreview-279024164

2019-08-23 15:51 UTC, wbhart commented
Consider len = 1. Then num[2 - 1] would have been zero, i.e. there would be one nonzero coefficient, namely num[0].

2019-08-26 05:56 UTC, fieker commented
I think it is even more hilariously wrong: there is no len for quadratics.
Quadratics are a strange structure....
I'll have a look again.

2019-08-26 11:45 UTC, wbhart approved these changes

2019-08-26 11:46 UTC, merged